### ISSUE TITLE
Provide RHEL6 compatible Linux pngcrush binary

### ISSUE THREAD

**Issue by sit** [imagemin/pngcrush-bin#8]
On RHEL6, the pre-built binary provided fails with:
```
vendor/pngcrush: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by vendor/pngcrush)
```
This means pngcrush-bin must fallback to building from source. However, due to the way that the maintainers of pngcrush organize their source folders, this path is unstable and can change over time and break builds that depend on a working pngcrush binary.

This can be rectified either by keeping up with the upstream paths (e.g., in #7) but it would be simpler to provide a stable version that is built against GLIBC_2.12 for RHEL6 as a separate binary. Then the detection code could simply choose the appropriate version of pngcrush based on the available glibc. 

This would be both faster (no need to download and build) and more reliable (no dependency on upstream paths remaining stable).

**Comment by erikmunson** [comment]
@esit Here is a binary built on GLIBC https://www.dropbox.com/s/dn4rw30k1k107r5/pngcrush?dl=0

**Comment by shinnn** [comment]
@erikmunson is it v1.7.83 binary?

**Comment by erikmunson** [comment]
@shinnn It is.

**Comment by shinnn** [comment]
@erikmunson Thanks. I replaced the current Linux binary with yours.

**Comment by erikmunson** [comment]
@shinnn happy I could help :)

**Comment by kevva** [comment]
Is it tested with on a system running an older version of GLIBC?

**Comment by erikmunson** [comment]
@kevva It's compiled on 2.12 running on RHEL6, untested on older versions. Might be a good idea to start checking the GLIBC version and choosing an appropriate binary based on that, similar to what the issue description suggests.

**Comment by kevva** [comment]
@erikmunson, great!
